### ISSUE TITLE
Shutdown exception

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/net-mdns#55]
When testing IPFS engine disposing, the following exception is thrown.

```
11:15:49.334 [ERROR] Makaretu.Dns.MulticastService - Receive handler failed
=======================================================(inner most exception)===
 (1) System.NullReferenceException
================================================================================
Method        :  Send
Type          :  Makaretu.Dns.MulticastService
Assembly      :  Makaretu.Dns.Multicast, Version=0.17.2.0, Culture=neutral, PublicKeyToken=null
Assembly Path :  C:\Users\Owner\Documents\GitHub\net-ipfs-engine\test\bin\Debug\net461\Makaretu.Dns.Multicast.dll
Source        :  Makaretu.Dns.Multicast
Thread        :  15 ''
Helplink      :  

Message:
"Object reference not set to an instance of an object."

Stack Trace:
   at Makaretu.Dns.MulticastService.Send(Message msg, Boolean checkDuplicate)
   at Makaretu.Dns.MulticastService.SendAnswer(Message answer, Boolean checkDuplicate)
   at Makaretu.Dns.ServiceDiscovery.OnQuery(Object sender, MessageEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Makaretu.Dns.MulticastService.OnDnsMessage(Object sender, UdpReceiveResult result)
================================================================================

```

**Comment by richardschneider** [comment]
The client can be disposed when there are messages still queued.
